# This is a basic workflow to help you get started with Actions

name: Self Hosted

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "benchmark"
  benchmark:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Publish Report
      - name: Publish Report
        run: ./Publish-Report.ps1

      # Run tests
      - name: Unit Test
        run: Invoke-Pester

      # Upload an artifact
      - name: Upload an artifact
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: report.txt
